# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-03 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200501_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='checkNote',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
